PERL_HTTP_TINY_VERSION = 0.076
PERL_HTTP_TINY_SOURCE = HTTP-Tiny-$(PERL_HTTP_TINY_VERSION).tar.gz
PERL_HTTP_TINY_SITE = $(BR2_CPAN_MIRROR)/authors/id/D/DA/DAGOLDEN
PERL_HTTP_TINY_LICENSE = BSD-4-Clause-like
PERL_HTTP_TINY_LICENSE_FILES = COPYRIGHT
PERL_HTTP_TINY_DISTNAME = HTTP-Tiny
PERL_HTTP_TINY_CONF_ENV = PATH=$(BR_PATH):$(HOST_DIR)/bin

$(eval $(perl-package))
