PERL_MOZILLA_CA_VERSION = 20200520
PERL_MOZILLA_CA_SOURCE = Mozilla-CA-$(PERL_MOZILLA_CA_VERSION).tar.gz
PERL_MOZILLA_CA_SITE = $(BR2_CPAN_MIRROR)/authors/id/A/AB/ABH
PERL_MOZILLA_CA_LICENSE = BSD-4-Clause-like
PERL_MOZILLA_CA_LICENSE_FILES = COPYRIGHT
PERL_MOZILLA_CA_DISTNAME = Mozilla-CA

$(eval $(perl-package))
