PERL_BYTES_RANDOM_SECURE_TINY_VERSION = 1.008
PERL_BYTES_RANDOM_SECURE_TINY_SOURCE = Bytes-Random-Secure-Tiny-$(PERL_BYTES_RANDOM_SECURE_TINY_VERSION).tar.gz
PERL_BYTES_RANDOM_SECURE_TINY_SITE = $(BR2_CPAN_MIRROR)/authors/id/D/DA/DAVIDO
PERL_BYTES_RANDOM_SECURE_TINY_LICENSE = BSD-4-Clause-like
PERL_BYTES_RANDOM_SECURE_TINY_LICENSE_FILES = COPYRIGHT
PERL_BYTES_RANDOM_SECURE_TINY_DISTNAME = Bytes-Random-Secure-Tiny
PERL_BYTES_RANDOM_SECURE_TINY_CONF_ENV = PATH=$(BR_PATH):$(HOST_DIR)/bin

$(eval $(perl-package))
