LIBMILTER_VERSION = 1.0.2
LIBMILTER_SITE = ftp://ftp.sendmail.org/pub/sendmail
LIBMILTER_SOURCE = sendmail.8.15.2.tar.gz
LIBMILTER_INSTALL_STAGING = YES
LIBMILTER_LICENSE = EPL-2.0, IPL-1.0
LIBMILTER_LICENSE_FILES = COPYING
LIBMILTER_DEPENDENCIES = host-m4

define LIBMILTER_BUILD_CMDS
	$(MAKE) -j1 -C $(@D)/libmilter M4=$(HOST_DIR)/bin/m4 CC=$(TARGET_CC) MILTER_SOVER=$(LIBMILTER_VERSION)
endef

define LIBMILTER_INSTALL_TARGET_CMDS
	$(MAKE) -j1 -C $(@D)/libmilter \
		MILTER_SOVER=$(LIBMILTER_VERSION) \
		INCOWN=root INCGRP=root INCMODE=644 \
		LIBOWN=root LIBGRP=root LIBMODE=644 UBINMODE=755 \
		DESTDIR="$(STAGING_DIR)" \
		install
endef

$(eval $(generic-package))
