PERL_CALL_CONTEXT_VERSION = 0.03
PERL_CALL_CONTEXT_SOURCE = Call-Context-$(PERL_CALL_CONTEXT_VERSION).tar.gz
PERL_CALL_CONTEXT_SITE = $(BR2_CPAN_MIRROR)/authors/id/F/FE/FELIPE
PERL_CALL_CONTEXT_LICENSE = BSD-4-Clause-like
PERL_CALL_CONTEXT_LICENSE_FILES = COPYRIGHT
PERL_CALL_CONTEXT_DISTNAME = Call-Context
PERL_CALL_CONTEXT_CONF_ENV = PATH=$(BR_PATH):$(HOST_DIR)/bin

$(eval $(perl-package))
