PERL_CLASS_ACCESSOR_VERSION = 0.51
PERL_CLASS_ACCESSOR_SOURCE = Class-Accessor-$(PERL_CLASS_ACCESSOR_VERSION).tar.gz
PERL_CLASS_ACCESSOR_SITE = $(BR2_CPAN_MIRROR)/authors/id/K/KA/KASEI
PERL_CLASS_ACCESSOR_LICENSE = BSD-4-Clause-like
PERL_CLASS_ACCESSOR_LICENSE_FILES = COPYRIGHT
PERL_CLASS_ACCESSOR_DISTNAME = Class-Accessor
PERL_CLASS_ACCESSOR_CONF_ENV = PATH=$(BR_PATH):$(HOST_DIR)/bin

$(eval $(perl-package))
