PERL_SYMBOL_GET_VERSION = 0.10
PERL_SYMBOL_GET_SOURCE = Symbol-Get-$(PERL_SYMBOL_GET_VERSION).tar.gz
PERL_SYMBOL_GET_SITE = $(BR2_CPAN_MIRROR)/authors/id/F/FE/FELIPE
PERL_SYMBOL_GET_LICENSE = BSD-4-Clause-like
PERL_SYMBOL_GET_LICENSE_FILES = COPYRIGHT
PERL_SYMBOL_GET_DISTNAME = Symbol-Get
PERL_SYMBOL_GET_CONF_ENV = PATH=$(BR_PATH):$(HOST_DIR)/bin

$(eval $(perl-package))
