PERL_MATH_PROVABLEPRIME_VERSION = 0.045
PERL_MATH_PROVABLEPRIME_SOURCE = Math-ProvablePrime-$(PERL_MATH_PROVABLEPRIME_VERSION).tar.gz
PERL_MATH_PROVABLEPRIME_SITE = $(BR2_CPAN_MIRROR)/authors/id/F/FE/FELIPE
PERL_MATH_PROVABLEPRIME_LICENSE = BSD-4-Clause-like
PERL_MATH_PROVABLEPRIME_LICENSE_FILES = COPYRIGHT
PERL_MATH_PROVABLEPRIME_DISTNAME = Math-ProvablePrime
PERL_MATH_PROVABLEPRIME_CONF_ENV = PATH=$(BR_PATH):$(HOST_DIR)/bin

$(eval $(perl-package))
